from kmap.render.likec4.model import (
    _is_url,
    external_model_systems,
    likec4_container_header_line,
    likec4_container_resource_lines,
    likec4_external_resource_lines,
    likec4_link_label,
    likec4_system_description,
    likec4_system_header_line,
    likec4_system_resource_lines,
    likec4_tag_lines,
    orphan_model_systems_by_project,
    project_model_systems,
    render_likec4_model,
    render_likec4_model_files,
)
from kmap.render.likec4.relations import render_likec4_relation_files


def minimal_architecture():
    return {
        "workspace": {
            "generated_at": "2026-04-28T10:00:00Z",
            "generator": {
                "tool": "kmap",
                "version": "0.1.0",
                "config_file": "config/demo.yaml",
                "rules_file": "GENERATION_RULES.md",
            },
        },
        "product": {"name": "demo", "title": "Demo"},
        "projects": [
            {"id": "prj.demo.api", "name": "api", "title": "API", "owner_team": "Team"},
        ],
        "systems": [
            {"id": "sys.demo.api.api", "project_id": "prj.demo.api", "name": "api", "title": "API"},
            {"id": "ext.database_mysql", "name": "Database", "title": "Database", "element_type": "MySQL_DB"},
        ],
        "containers": [
            {
                "id": "ctr.demo.api.api.app",
                "system_id": "sys.demo.api.api",
                "name": "app",
                "title": "App",
                "technology": "Go",
            }
        ],
        "relationships": [
            {
                "id": "rel.1",
                "source_id": "ctr.demo.api.api.app",
                "target_id": "ext.database_mysql",
                "type": "mysql",
                "title": "MYSQL_DSN",
                "evidence": [{"kind": "env", "source": "MYSQL_DSN", "value": "MYSQL_DSN=mysql://demo"}],
                "boundary": {"kind": "project_to_external"},
            }
        ],
    }


def test_likec4_model_focused_golden():
    assert render_likec4_model(minimal_architecture()) == (
        "model {\n"
        "  // Generated by kmap. Do not edit manually.\n"
        "\n"
        '  ext_database_mysql = MySQL_DB "Database" {\n'
        "  }\n"
        "\n"
        '  sys_demo_api_api = system "API" {\n'
        "    metadata {\n"
        '      project "api"\n'
        '      project_title "API"\n'
        '      devops "Team"\n'
        "    }\n"
        '    ctr_demo_api_api_app = container "App" {\n'
        '      technology "Go"\n'
        "    }\n"
        "  }\n"
        "\n"
        "}\n"
    )


def test_likec4_model_header_helpers_preserve_rendered_line_format():
    assert likec4_system_header_line("sys_pay", "GoLang_App", 'Pay "API"') == '  sys_pay = GoLang_App "Pay \\"API\\"" {'
    assert likec4_container_header_line("ctr_pay_api", "container", "API") == '    ctr_pay_api = container "API" {'


def test_likec4_model_partition_helpers_split_external_project_and_orphan_systems():
    systems = [
        {"id": "sys.api", "project_id": "prj.api"},
        {"id": "sys.worker", "project_id": "prj.worker"},
        {"id": "sys.legacy", "project_id": "legacy"},
        {"id": "ext.docs", "tags": ["External"]},
        {"id": "ext.no.project"},
    ]

    assert [system["id"] for system in external_model_systems(systems)] == ["ext.docs", "ext.no.project"]
    assert [system["id"] for system in project_model_systems(systems, "prj.api")] == ["sys.api"]
    assert orphan_model_systems_by_project(systems, {"prj.api", "prj.worker"}) == {
        "legacy": [{"id": "sys.legacy", "project_id": "legacy"}]
    }


def test_likec4_external_endpoint_containers_use_external_element_type():
    architecture = minimal_architecture()
    architecture["containers"].append(
        {
            "id": "extc.database_mysql.primary",
            "system_id": "ext.database_mysql",
            "name": "mysql-primary",
            "title": "MySQL Primary",
            "kind": "external",
            "technology": "External dependency",
        }
    )

    rendered = render_likec4_model(architecture)

    assert 'extc_database_mysql_primary = MySQL_DB "MySQL Primary" {' in rendered
    assert 'extc_database_mysql_primary = container "MySQL Primary" {' not in rendered


def test_likec4_generic_external_endpoint_containers_use_neutral_type():
    architecture = minimal_architecture()
    architecture["systems"][1] = {
        "id": "ext.redash",
        "name": "Redash",
        "title": "Redash",
        "element_type": "system",
        "tags": ["External"],
    }
    architecture["containers"].append(
        {
            "id": "extc.redash.prod",
            "system_id": "ext.redash",
            "name": "redash-prod",
            "title": "Redash Prod",
            "kind": "external",
            "technology": "External dependency",
        }
    )

    rendered = render_likec4_model(architecture)

    assert 'extc_redash_prod = External_Endpoint "Redash Prod" {' in rendered
    assert 'extc_redash_prod = container "Redash Prod" {' not in rendered


def test_likec4_model_flattens_newlines_in_visible_descriptions():
    architecture = minimal_architecture()
    architecture["containers"].append(
        {
            "id": "extc.database_mysql.primary",
            "system_id": "ext.database_mysql",
            "name": "mysql-primary",
            "title": "MySQL Primary",
            "kind": "external",
            "technology": "External dependency",
            "description": "External dependency\\nEndpoint: mysql-primary",
        }
    )

    rendered = render_likec4_model(architecture)

    assert 'description "External dependency; Endpoint: mysql-primary"' in rendered
    assert "External dependency\\\\nEndpoint" not in rendered


def test_likec4_system_resource_lines_include_project_links():
    lines = likec4_system_resource_lines(
        {"project_id": "prj.pay"},
        {
            "prj.pay": {
                "name": "pay",
                "title": "Payments",
                "owner_team": "Platform",
                "domain_team": "Commerce",
                "description": "Payment service",
                "discovery": {"namespaces": ["payments", "payments"]},
                "resources": {"repo": "https://example.com/pay.git"},
            }
        },
    )

    assert "    metadata {" in lines
    assert '      project "pay"' in lines
    assert '      description "Payment service"' not in lines
    assert "repo" not in "\n".join(lines)
    assert "    link https://example.com/pay.git 'Repository'" in lines


def test_likec4_system_description_uses_system_then_project_description():
    projects = {"prj.pay": {"description": "Project description"}}

    assert likec4_system_description({"description": "System description", "project_id": "prj.pay"}, projects) == (
        "System description"
    )
    assert likec4_system_description({"project_id": "prj.pay"}, projects) == "Project description"


def test_likec4_system_resource_lines_skip_links_with_unsafe_url_syntax():
    lines = likec4_system_resource_lines(
        {"project_id": "prj.pay"},
        {
            "prj.pay": {
                "name": "pay",
                "resources": {"repo": 'https://example.com/"bad"\ninclude hacked'},
            }
        },
    )

    assert not any("repo" in line for line in lines)
    assert not any(line.strip().startswith("link ") for line in lines)


def test_likec4_container_resource_lines_include_project_links():
    lines = likec4_container_resource_lines(
        {"project_id": "prj.pay"},
        {
            "prj.pay": {
                "name": "pay",
                "resources": {"repo": "https://example.com/pay.git"},
            }
        },
    )

    assert lines == ["      link https://example.com/pay.git 'Repository'"]


def test_likec4_tag_lines_normalize_and_deduplicate_tags():
    assert likec4_tag_lines(["demo", "Backend", "team one", ""]) == [
        "    #demo",
        "    #Backend",
        "    #team_one",
    ]


def test_likec4_external_resource_lines_for_websites():
    assert likec4_external_resource_lines({"element_type": "Website", "title": "docs.example.com"}) == [
        "    metadata {",
        '      domain "docs.example.com"',
        '      url "https://docs.example.com"',
        "    }",
        "    link https://docs.example.com 'Website'",
    ]


def test_likec4_external_resource_lines_skip_unsafe_website_links():
    assert likec4_external_resource_lines({"element_type": "Website", "title": 'https://bad.example.com/"oops"'}) == []


def test_likec4_url_detection_requires_http_url_with_host():
    assert _is_url("") is False
    assert _is_url("docs.example.com") is False
    assert _is_url("ftp://docs.example.com") is False
    assert _is_url("https://docs.example.com") is True


def test_likec4_external_resource_lines_skip_non_url_safe_website_titles():
    assert likec4_external_resource_lines({"element_type": "Website", "title": "Docs Portal"}) == []


def test_likec4_external_resource_lines_normalize_internal_website_domains():
    lines = likec4_external_resource_lines(
        {"element_type": "Website", "title": "https://vault-prod.demo.service.demo.consul:8200"}
    )

    assert '      domain "vault-prod"' in lines
    assert "    link https://vault-prod.demo.service.demo.consul:8200 'Website'" in lines


def test_likec4_external_resource_lines_skip_generic_website_titles():
    assert likec4_external_resource_lines({"element_type": "Website", "title": "Website"}) == []
    assert likec4_external_resource_lines({"element_type": "system", "title": "docs.example.com"}) == []


def test_likec4_link_label_humanizes_unknown_keys():
    assert likec4_link_label("repo") == "Repository"
    assert likec4_link_label("runbook_url") == "Runbook Url"
    assert likec4_link_label("404_link") == "404 Link"


def test_render_likec4_model_outputs_systems_containers_and_metadata():
    rendered = render_likec4_model(
        {
            "projects": [
                {
                    "id": "prj.pay",
                    "name": "pay",
                    "title": "Payments",
                    "description": "Payment service",
                    "discovery": {"namespaces": ["pay-prod"]},
                    "resources": {"repo": "https://example.com/pay.git"},
                    "tags": ["payments"],
                }
            ],
            "systems": [
                {
                    "id": "sys.pay",
                    "name": "pay",
                    "title": "Pay",
                    "project_id": "prj.pay",
                    "element_type": "GoLang_App",
                }
            ],
            "containers": [
                {
                    "id": "ctr.pay.api",
                    "name": "api",
                    "title": "API",
                    "system_id": "sys.pay",
                    "technology": "Go",
                    "discovery": {"clusters": ["cluster-1"]},
                    "runtime": {
                        "container_kinds": ["container"],
                        "images": ["example/api:1"],
                        "container_ports": ["8080/TCP"],
                    },
                    "name_source": {"raw_container_name": "api-prod"},
                }
            ],
        }
    )

    assert 'sys_pay = GoLang_App "Pay"' in rendered
    assert "    #payments" in rendered
    assert '  description "Payment service"' in rendered
    assert '      description "Payment service"' not in rendered
    assert "link https://example.com/pay.git 'Repository'" in rendered
    assert 'repo "https://example.com/pay.git"' not in rendered
    assert 'ctr_pay_api = container "API"' in rendered
    assert "      #payments" in rendered
    assert rendered.index("      #payments") < rendered.index('      technology "Go"')
    assert "      link https://example.com/pay.git 'Repository'" in rendered
    assert 'technology "Go"' in rendered
    assert 'namespaces "pay-prod"' not in rendered
    assert 'clusters "cluster-1"' not in rendered
    assert 'container_image "example/api:1"' in rendered
    assert 'ops_network "container ports: 8080/TCP"' in rendered
    assert 'container_source "api-prod"' in rendered
    assert 'container_images "example/api:1"' not in rendered
    assert 'container_ports "8080/TCP"' not in rendered


def test_render_likec4_model_outputs_element_metadata_and_descriptions():
    rendered = render_likec4_model(
        {
            "systems": [
                {
                    "id": "sys.pay",
                    "title": "Pay",
                    "element_type": "Unknown_Type",
                    "metadata": {
                        "owner": "Payments",
                        "tags": ["critical", "critical", "pci"],
                        "empty_tags": ["", None],
                        "blank": "",
                    },
                },
                {
                    "id": "sys.ignored.metadata",
                    "title": "Ignored",
                    "metadata": ["not", "a", "mapping"],
                },
            ],
            "containers": [
                {
                    "id": "ctr.pay.api",
                    "title": "API",
                    "system_id": "sys.pay",
                    "description": "Handles payments\\nand refunds",
                }
            ],
        }
    )

    assert 'sys_pay = system "Pay"' in rendered
    assert 'owner "Payments"' in rendered
    assert 'tags "critical, pci"' in rendered
    assert "blank" not in rendered
    assert "empty_tags" not in rendered
    assert 'description "Handles payments; and refunds"' in rendered


def test_render_likec4_model_adds_autoscaling_metadata_from_deployments():
    rendered = render_likec4_model(
        {
            "projects": [{"id": "prj.pay", "name": "pay", "title": "Payments"}],
            "systems": [{"id": "sys.pay", "name": "pay", "title": "Pay", "project_id": "prj.pay"}],
            "containers": [
                {
                    "id": "ctr.pay.api",
                    "name": "api",
                    "title": "App",
                    "system_id": "sys.pay",
                }
            ],
            "deployments": [
                {
                    "env": "prod",
                    "clusters": [
                        {
                            "namespaces": [
                                {
                                    "instances": [
                                        {
                                            "container_id": "ctr.pay.api",
                                            "runtime": {
                                                "services": ["api-svc"],
                                                "storage_types": ["configMap"],
                                                "service_account": ["api-sa"],
                                                "scaling_enabled": ["true"],
                                                "scaling_type": ["hpa"],
                                                "min_replicas": ["2"],
                                                "max_replicas": ["4"],
                                                "scale_formula": ["cpu averageUtilization 400"],
                                            },
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                }
            ],
        }
    )

    assert 'description "Autoscaling:' not in rendered
    assert "      metadata {" in rendered
    assert (
        '        ops_scaling "enabled: true; type: hpa; min: 2; max: 4; formula: cpu averageUtilization 400"'
        in rendered
    )
    assert '        ops_network "services: api-svc"' in rendered
    assert '        ops_storage "types: configMap"' in rendered
    assert '        ops_security "service account: api-sa"' in rendered


def test_render_likec4_model_dedupes_deployment_metadata_from_multiple_instances():
    rendered = render_likec4_model(
        {
            "systems": [{"id": "sys.pay", "title": "Pay"}],
            "containers": [{"id": "ctr.pay.api", "title": "App", "system_id": "sys.pay"}],
            "deployments": [
                {
                    "clusters": [
                        {
                            "namespaces": [
                                {
                                    "instances": [
                                        {
                                            "container_id": "ctr.pay.api",
                                            "runtime": {
                                                "services": ["api-svc", "api-svc"],
                                                "storage_types": ["configMap"],
                                            },
                                        },
                                        {
                                            "container_id": "ctr.pay.api",
                                            "runtime": {
                                                "services": ["api-svc", "api-metrics"],
                                                "storage_types": ["configMap", "secret"],
                                            },
                                        },
                                        {"container_id": "", "runtime": {"services": ["ignored"]}},
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
        }
    )

    assert 'ops_network "services: api-svc, api-metrics"' in rendered
    assert rendered.count("api-svc") == 1
    assert rendered.count("api-metrics") == 1
    assert 'ops_storage "types: configMap, secret"' in rendered
    assert "ignored" not in rendered


def test_render_likec4_model_flattens_nested_deployment_metadata_values():
    rendered = render_likec4_model(
        {
            "systems": [{"id": "sys.pay", "title": "Pay"}],
            "containers": [{"id": "ctr.pay.api", "title": "App", "system_id": "sys.pay"}],
            "deployments": [
                {
                    "clusters": [
                        {
                            "namespaces": [
                                {
                                    "instances": [
                                        {
                                            "container_id": "ctr.pay.api",
                                            "runtime": {
                                                "services": [["api-svc", ""], "api-svc", ["api-metrics"]],
                                            },
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
        }
    )

    assert 'ops_network "services: api-svc, api-metrics"' in rendered


def test_render_likec4_model_types_external_containers_from_external_systems():
    rendered = render_likec4_model(
        {
            "systems": [
                {"id": "ext.vault", "title": "Vault", "element_type": "Vault", "tags": ["External"]},
                {"id": "ext.website", "title": "Website", "element_type": "Website", "tags": ["External"]},
            ],
            "containers": [
                {"id": "ctr.ext.vault.api", "title": "Vault API", "system_id": "ext.vault", "kind": "external"},
                {"id": "ctr.ext.website.api", "title": "Website API", "system_id": "ext.website", "kind": "external"},
            ],
        }
    )

    assert 'ctr_ext_vault_api = Vault "Vault API"' in rendered
    assert 'ctr_ext_website_api = External_Endpoint "Website API"' in rendered


def test_likec4_model_and_relation_files_are_split_by_project_and_external():
    architecture = {
        "projects": [
            {"id": "prj.demo.api", "name": "api", "title": "API"},
            {"id": "prj.demo.worker", "name": "worker", "title": "Worker"},
        ],
        "systems": [
            {"id": "sys.demo.api", "project_id": "prj.demo.api", "title": "API"},
            {"id": "sys.demo.worker", "project_id": "prj.demo.worker", "title": "Worker"},
            {"id": "ext.docs", "title": "docs.example.com", "element_type": "Website", "tags": ["External"]},
        ],
        "containers": [
            {"id": "ctr.demo.api.app", "system_id": "sys.demo.api", "title": "App"},
            {"id": "ctr.demo.worker.app", "system_id": "sys.demo.worker", "title": "Worker"},
        ],
        "relationships": [
            {"id": "rel.1", "source_id": "ctr.demo.api.app", "target_id": "ext.docs", "title": "docs"},
            {
                "id": "rel.2",
                "source_id": "ctr.demo.api.app",
                "target_id": "ctr.demo.worker.app",
                "title": "worker",
            },
        ],
    }

    model_files = render_likec4_model_files(architecture)
    relation_files = render_likec4_relation_files(architecture)

    assert "ext_docs" in model_files["model/00-external.c4"]
    assert "sys_demo_api" not in model_files["model/00-external.c4"]
    assert "sys_demo_api" in model_files["model/projects/api.c4"]
    assert "sys_demo_worker" not in model_files["model/projects/api.c4"]
    assert "ext_docs" in relation_files["model/relations/00-external.c4"]
    assert "sys_demo_worker.ctr_demo_worker_app" in relation_files["model/relations/api.c4"]


def test_likec4_model_files_deduplicate_project_paths_and_render_orphan_project_systems():
    architecture = {
        "projects": [
            {"id": "prj.pay.api", "name": "pay", "title": "Pay API"},
            {"id": "pay", "name": "pay", "title": "Pay Duplicate"},
            {"id": "prj.pay.worker", "name": "pay", "title": "Pay Worker"},
            {"id": "prj.pay.worker.copy", "name": "pay", "title": "Pay Worker Copy"},
            {"id": "prj.empty", "name": "empty", "title": "Empty"},
        ],
        "systems": [
            {"id": "sys.pay.api", "project_id": "prj.pay.api", "title": "API"},
            {"id": "sys.pay.duplicate", "project_id": "pay", "title": "Duplicate"},
            {"id": "sys.pay.worker", "project_id": "prj.pay.worker", "title": "Worker"},
            {"id": "sys.pay.worker.copy", "project_id": "prj.pay.worker.copy", "title": "Worker Copy"},
            {"id": "sys.legacy", "project_id": "legacy-project", "title": "Legacy"},
        ],
        "containers": [],
    }

    model_files = render_likec4_model_files(architecture)

    assert "model/projects/pay.c4" in model_files
    assert "model/projects/pay-2.c4" in model_files
    assert "model/projects/prj-pay-worker.c4" in model_files
    assert "model/projects/prj-pay-worker-copy.c4" in model_files
    assert "model/projects/empty.c4" not in model_files
    assert "model/projects/legacy-project.c4" in model_files
    assert "sys_legacy" in model_files["model/projects/legacy-project.c4"]
