import json
from argparse import Namespace

from kmap.render.likec4 import render_likec4


def test_render_likec4_writes_project_files(tmp_path):
    architecture_file = tmp_path / "architecture.json"
    output_dir = tmp_path / "likec4"
    output_dir.mkdir()
    (output_dir / "model").mkdir()
    (output_dir / "model" / "product.c4").write_text(
        "model {\n  // Generated by kmap. Do not edit manually.\n}\n",
        encoding="utf-8",
    )
    (output_dir / "model" / "relations.c4").write_text(
        "model {\n  // Generated relationships by kmap. Do not edit manually.\n}\n",
        encoding="utf-8",
    )
    architecture_file.write_text(
        json.dumps(
            {
                "workspace": {"generator": {"tool": "kmap", "version": "0.1.0", "rules_file": "GENERATION_RULES.md"}},
                "product": {"name": "demo", "title": "Demo", "tags": ["demo"]},
                "projects": [{"id": "prj.demo.api", "name": "api", "title": "API", "tags": ["backend"]}],
                "systems": [
                    {"id": "sys.demo.api", "project_id": "prj.demo.api", "title": "API"},
                    {"id": "ext.docs", "title": "docs.example.com", "element_type": "Website", "tags": ["External"]},
                ],
                "containers": [{"id": "ctr.demo.api.app", "system_id": "sys.demo.api", "title": "App"}],
                "relationships": [
                    {"id": "rel.1", "source_id": "ctr.demo.api.app", "target_id": "ext.docs", "title": "docs"}
                ],
                "deployments": [
                    {
                        "env": "prod",
                        "clusters": [
                            {
                                "id": "cluster-main",
                                "name": "cluster-main",
                                "namespaces": [
                                    {
                                        "id": "ns-api",
                                        "name": "api",
                                        "instances": [
                                            {
                                                "id": "pod-api",
                                                "name": "api",
                                                "container_id": "ctr.demo.api.app",
                                            }
                                        ],
                                    }
                                ],
                            }
                        ],
                    }
                ],
            }
        ),
        encoding="utf-8",
    )

    rc = render_likec4(
        Namespace(
            architecture_file=str(architecture_file),
            output_dir=str(output_dir),
            common_path="../common",
        )
    )

    assert rc == 0
    assert (output_dir / "likec4.config.json").exists()
    assert not (output_dir / "model" / "product.c4").exists()
    assert not (output_dir / "model" / "relations.c4").exists()
    assert (output_dir / "model" / "00-external.c4").exists()
    assert (output_dir / "model" / "projects" / "api.c4").exists()
    assert (output_dir / "model" / "relations" / "00-external.c4").exists()
    manifest = json.loads((output_dir / "model" / ".kmap-generated.json").read_text(encoding="utf-8"))
    assert manifest["kind"] == "likec4-model"
    assert manifest["files"] == [
        "model/00-external.c4",
        "model/projects/api.c4",
        "model/relations/00-external.c4",
    ]
    assert (output_dir / "deployments" / "prod.c4").exists()
    assert (output_dir / "specification" / "generated.c4").read_text(encoding="utf-8") == (
        "specification {\n  // Generated config tags by kmap. Do not edit manually.\n  tag demo\n  tag backend\n}\n"
    )
    generated_views = (output_dir / "views" / "generated.c4").read_text(encoding="utf-8")
    assert "deployment view demo_prod_deployment" in generated_views
    assert "deployment view demo_prod_cluster_main_ns_api_pod_api_containers" in generated_views
    assert "include demo_prod.cluster_main.ns_api.pod_api.*" in generated_views
    assert (output_dir / "README.md").exists()


def test_render_likec4_removes_manifest_stale_files_but_keeps_curated_files(tmp_path):
    architecture_file = tmp_path / "architecture.json"
    output_dir = tmp_path / "likec4"
    (output_dir / "model" / "projects").mkdir(parents=True)
    stale = output_dir / "model" / "projects" / "old-project.c4"
    curated = output_dir / "model" / "projects" / "curated.c4"
    outside = output_dir / "keep.c4"
    stale.write_text("stale generated content\n", encoding="utf-8")
    curated.write_text('model {\n  curated = system "Curated"\n}\n', encoding="utf-8")
    outside.write_text("keep me\n", encoding="utf-8")
    (output_dir / "model" / ".kmap-generated.json").write_text(
        json.dumps(
            {
                "generator": "kmap",
                "kind": "likec4-model",
                "files": ["model/projects/old-project.c4", "model/../keep.c4"],
            }
        ),
        encoding="utf-8",
    )
    architecture_file.write_text(
        json.dumps(
            {
                "product": {"name": "demo", "title": "Demo"},
                "projects": [{"id": "prj.demo.api", "name": "api", "title": "API"}],
                "systems": [{"id": "sys.demo.api", "project_id": "prj.demo.api", "title": "API"}],
                "containers": [{"id": "ctr.demo.api.app", "system_id": "sys.demo.api", "title": "App"}],
                "relationships": [],
            }
        ),
        encoding="utf-8",
    )

    rc = render_likec4(
        Namespace(
            architecture_file=str(architecture_file),
            output_dir=str(output_dir),
            common_path="../common",
        )
    )

    assert rc == 0
    assert not stale.exists()
    assert curated.exists()
    assert outside.exists()
    assert (output_dir / "model" / "projects" / "api.c4").exists()
