import json
from argparse import Namespace

from kmap.render.structurizr.architecture import render_structurizr_architecture, render_structurizr_workspace


def minimal_architecture():
    return {
        "workspace": {
            "generated_at": "2026-04-28T10:00:00Z",
            "generator": {
                "tool": "kmap",
                "version": "0.1.0",
                "config_file": "config/demo.yaml",
                "rules_file": "GENERATION_RULES.md",
            },
        },
        "product": {"name": "demo", "title": "Demo"},
        "projects": [
            {"id": "prj.demo.api", "name": "api", "title": "API", "owner_team": "Team"},
        ],
        "systems": [
            {"id": "sys.demo.api.api", "project_id": "prj.demo.api", "name": "api", "title": "API"},
            {"id": "ext.database_mysql", "name": "Database", "title": "Database", "element_type": "MySQL_DB"},
        ],
        "containers": [
            {
                "id": "ctr.demo.api.api.app",
                "system_id": "sys.demo.api.api",
                "name": "app",
                "title": "App",
                "technology": "Go",
            }
        ],
        "relationships": [
            {
                "id": "rel.1",
                "source_id": "ctr.demo.api.api.app",
                "target_id": "ext.database_mysql",
                "type": "mysql",
                "title": "MYSQL_DSN",
                "evidence": [{"kind": "env", "source": "MYSQL_DSN", "value": "MYSQL_DSN=mysql://demo"}],
                "boundary": {"kind": "project_to_external"},
            }
        ],
    }


def test_structurizr_workspace_focused_golden():
    assert render_structurizr_workspace(minimal_architecture()) == (
        "// Generated by kmap 0.1.0 at 2026-04-28T10:00:00Z\n"
        "// Config: config/demo.yaml\n"
        "// Rules: GENERATION_RULES.md\n"
        "workspace extends ../common/workspace.dsl {\n"
        '    name "demo"\n'
        '    description "Описание архитектуры"\n'
        "    properties {\n"
        '        "kmap.generator" "kmap"\n'
        '        "kmap.generator.version" "0.1.0"\n'
        '        "kmap.generated_at" "2026-04-28T10:00:00Z"\n'
        '        "kmap.config_file" "config/demo.yaml"\n'
        '        "kmap.rules_file" "GENERATION_RULES.md"\n'
        "    }\n"
        "    model {\n"
        "        !include model/projects/\n"
        "        !include model/external/\n"
        "        !include model/relations/\n"
        "        !include deployment/\n"
        "    }\n"
        "    views {\n"
        "        !include view/\n"
        "    }\n"
        "}\n"
    )


def test_render_structurizr_architecture_writes_model_and_views(tmp_path):
    architecture_file = tmp_path / "architecture.json"
    output_dir = tmp_path / "Structurizr" / "demo"
    (output_dir / "model").mkdir(parents=True)
    (output_dir / "model" / "generated.dsl").write_text("legacy generated content\n", encoding="utf-8")
    architecture_file.write_text(json.dumps(minimal_architecture()), encoding="utf-8")

    rc = render_structurizr_architecture(
        Namespace(architecture_file=str(architecture_file), output_dir=str(output_dir))
    )

    assert rc == 0
    assert not (output_dir / "model" / "generated.dsl").exists()
    assert (
        (output_dir / "model" / "projects" / "api.dsl")
        .read_text(encoding="utf-8")
        .startswith("// Generated model for project api by kmap.")
    )
    assert (output_dir / "model" / "external" / "00-external.dsl").exists()
    assert (output_dir / "model" / "relations" / "00-external.dsl").exists()
    manifest = json.loads((output_dir / "model" / ".kmap-generated.json").read_text(encoding="utf-8"))
    assert manifest["kind"] == "structurizr-model"
    assert manifest["files"] == [
        "model/external/00-external.dsl",
        "model/projects/api.dsl",
        "model/relations/00-external.dsl",
    ]
    assert (output_dir / "view" / "generated.dsl").read_text(encoding="utf-8").startswith("systemLandscape landscape")
    assert (output_dir / "deployment" / "generated.dsl").read_text(encoding="utf-8") == "# Generated by kmap.py\n"
    assert (output_dir / "workspace.dsl").read_text(encoding="utf-8").startswith("// Generated by kmap 0.1.0")


def test_render_structurizr_architecture_writes_deployment_from_model(tmp_path):
    architecture = minimal_architecture()
    architecture["deployments"] = [
        {
            "env": "prod",
            "clusters": [
                {
                    "id": "cluster-1",
                    "name": "cluster-1",
                    "namespaces": [
                        {
                            "id": "ns-pay",
                            "name": "payments",
                            "project_id": "prj.demo.api",
                            "instances": [
                                {
                                    "id": "pod-api",
                                    "name": "api",
                                    "container_id": "ctr.demo.api.api.app",
                                    "node_kind": "k8s_pod",
                                    "runtime": {"replicas_desired": [1]},
                                }
                            ],
                        }
                    ],
                }
            ],
        }
    ]
    architecture_file = tmp_path / "architecture.json"
    output_dir = tmp_path / "Structurizr" / "demo"
    architecture_file.write_text(json.dumps(architecture), encoding="utf-8")

    rc = render_structurizr_architecture(
        Namespace(architecture_file=str(architecture_file), output_dir=str(output_dir))
    )

    assert rc == 0
    deployment = (output_dir / "deployment" / "generated.dsl").read_text(encoding="utf-8")
    assert 'deploymentEnvironment "prod"' in deployment
    assert "instances 1" in deployment
    assert "containerInstance ctr_demo_api_api_app" in deployment


def test_render_structurizr_architecture_removes_manifest_stale_files_but_keeps_curated_files(tmp_path):
    architecture_file = tmp_path / "architecture.json"
    output_dir = tmp_path / "Structurizr" / "demo"
    (output_dir / "model" / "projects").mkdir(parents=True)
    stale = output_dir / "model" / "projects" / "old-project.dsl"
    curated = output_dir / "model" / "projects" / "curated.dsl"
    outside = output_dir / "keep.dsl"
    stale.write_text("stale generated content\n", encoding="utf-8")
    curated.write_text('curated = softwareSystem "Curated"\n', encoding="utf-8")
    outside.write_text("keep me\n", encoding="utf-8")
    (output_dir / "model" / ".kmap-generated.json").write_text(
        json.dumps(
            {
                "generator": "kmap",
                "kind": "structurizr-model",
                "files": ["model/projects/old-project.dsl", "model/../keep.dsl"],
            }
        ),
        encoding="utf-8",
    )
    architecture_file.write_text(json.dumps(minimal_architecture()), encoding="utf-8")

    rc = render_structurizr_architecture(
        Namespace(architecture_file=str(architecture_file), output_dir=str(output_dir))
    )

    assert rc == 0
    assert not stale.exists()
    assert curated.exists()
    assert outside.exists()
    assert (output_dir / "model" / "projects" / "api.dsl").exists()
