from kmap.render.structurizr.model_files import (
    generated_fragment,
    render_structurizr_model_files,
)


def test_generated_fragment_prepends_comment():
    assert generated_fragment("Generated by tests.", "content\n") == "// Generated by tests.\ncontent\n"


def minimal_architecture():
    return {
        "workspace": {
            "generated_at": "2026-04-28T10:00:00Z",
            "generator": {
                "tool": "kmap",
                "version": "0.1.0",
                "config_file": "config/demo.yaml",
                "rules_file": "GENERATION_RULES.md",
            },
        },
        "product": {"name": "demo", "title": "Demo"},
        "projects": [
            {"id": "prj.demo.api", "name": "api", "title": "API", "owner_team": "Team"},
        ],
        "systems": [
            {"id": "sys.demo.api.api", "project_id": "prj.demo.api", "name": "api", "title": "API"},
            {"id": "ext.database_mysql", "name": "Database", "title": "Database", "element_type": "MySQL_DB"},
        ],
        "containers": [
            {
                "id": "ctr.demo.api.api.app",
                "system_id": "sys.demo.api.api",
                "name": "app",
                "title": "App",
                "technology": "Go",
            }
        ],
        "relationships": [
            {
                "id": "rel.1",
                "source_id": "ctr.demo.api.api.app",
                "target_id": "ext.database_mysql",
                "type": "mysql",
                "title": "MYSQL_DSN",
                "evidence": [{"kind": "env", "source": "MYSQL_DSN", "value": "MYSQL_DSN=mysql://demo"}],
                "boundary": {"kind": "project_to_external"},
            }
        ],
    }


def test_render_structurizr_model_files_deduplicate_paths_and_render_orphan_projects():
    architecture = {
        "product": {"name": "demo"},
        "projects": [
            {"id": "prj.demo.api", "name": "api", "title": "API"},
            {"id": "api", "name": "api", "title": "API Duplicate"},
            {"id": "prj.demo.worker", "name": "api", "title": "Worker"},
            {"id": "prj.empty", "name": "empty", "title": "Empty"},
        ],
        "systems": [
            {"id": "sys.demo.api", "project_id": "prj.demo.api", "title": "API"},
            {"id": "sys.demo.api.duplicate", "project_id": "api", "title": "API Duplicate"},
            {"id": "sys.demo.worker", "project_id": "prj.demo.worker", "title": "Worker"},
            {"id": "sys.demo.orphan", "project_id": "legacy-project", "title": "Legacy"},
            {"id": "ext.search", "title": "Search"},
        ],
        "containers": [
            {"id": "ctr.demo.api", "system_id": "sys.demo.api", "title": "API"},
            {"id": "ctr.demo.worker", "system_id": "sys.demo.worker", "title": "Worker"},
            {"id": "ctr.ext.search", "system_id": "ext.search", "title": "Search Endpoint"},
        ],
        "relationships": [
            {"id": "rel.1", "source_id": "ctr.demo.api", "target_id": "ctr.demo.worker", "type": "tcp"},
            {"id": "rel.2", "source_id": "ext.search", "target_id": "ctr.demo.api", "type": "tcp"},
            {"id": "rel.3", "source_id": "ctr.demo.worker", "target_id": "ctr.ext.search", "type": "tcp"},
            {"id": "rel.ignored", "source_id": "ctr.demo.api", "target_id": "missing", "type": "tcp"},
        ],
    }

    files = render_structurizr_model_files(architecture)

    assert "model/projects/api.dsl" in files
    assert "model/projects/api-2.dsl" in files
    assert "model/projects/prj-demo-worker.dsl" in files
    assert "model/projects/legacy-project.dsl" in files
    assert "model/projects/empty.dsl" not in files
    assert "model/relations/api.dsl" in files
    assert "model/relations/00-external.dsl" in files
    assert "model/relations/prj-demo-worker.dsl" not in files
    assert "sys_demo_orphan" in files["model/projects/legacy-project.dsl"]
    assert (
        'extsys_org_demo_external_mapped_Search -> ctr_demo_api "uses" "tcp"'
        in files["model/relations/00-external.dsl"]
    )
    assert (
        'ctr_demo_worker -> extc_org_demo_external_Search_Endpoint "uses" "tcp"'
        in files["model/relations/00-external.dsl"]
    )
    assert "missing" not in "".join(files.values())


def test_structurizr_model_files_are_split_and_deduplicate_relationships():
    architecture = minimal_architecture()
    architecture["projects"].append({"id": "prj.demo.worker", "name": "worker", "title": "Worker"})
    architecture["systems"].append(
        {"id": "sys.demo.worker", "project_id": "prj.demo.worker", "name": "worker", "title": "Worker"}
    )
    architecture["containers"].append(
        {
            "id": "ctr.demo.worker.app",
            "system_id": "sys.demo.worker",
            "name": "worker",
            "title": "Worker",
        }
    )
    architecture["relationships"].extend(
        [
            {
                "id": "rel.2",
                "source_id": "ctr.demo.api.api.app",
                "target_id": "ctr.demo.worker.app",
                "type": "tcp",
            },
            {
                "id": "rel.3",
                "source_id": "ctr.demo.api.api.app",
                "target_id": "ctr.demo.worker.app",
                "type": "https",
            },
            {
                "id": "rel.4",
                "source_id": "ext.database_mysql",
                "target_id": "ctr.demo.api.api.app",
                "type": "tcp",
            },
        ]
    )

    files = render_structurizr_model_files(architecture)

    assert 'sys_demo_api_api = softwareSystem "demo / API"' in files["model/projects/api.dsl"]
    assert 'sys_demo_worker = softwareSystem "demo / Worker"' in files["model/projects/worker.dsl"]
    assert "ext_org_demo_external_Database" in files["model/external/00-external.dsl"]
    assert "ext_org_demo_external_Database" in files["model/relations/00-external.dsl"]
    assert 'ext_org_demo_external_Database -> ctr_demo_api_api_app "uses"' in files["model/relations/00-external.dsl"]
    assert files["model/relations/api.dsl"].count('ctr_demo_api_api_app -> ctr_demo_worker_app "uses"') == 1
    assert "model/relations/worker.dsl" not in files


def test_structurizr_model_files_keep_projects_without_containers():
    architecture = minimal_architecture()
    architecture["projects"].append({"id": "prj.demo.empty", "name": "empty", "title": "Empty"})
    architecture["systems"].append(
        {"id": "sys.demo.empty", "project_id": "prj.demo.empty", "name": "empty", "title": "Empty"}
    )

    files = render_structurizr_model_files(architecture)

    assert 'sys_demo_empty = softwareSystem "demo / Empty" "Product scope"' in files["model/projects/empty.dsl"]


def test_structurizr_model_files_disambiguate_duplicate_system_titles_across_projects():
    architecture = {
        "workspace": {"org": "web"},
        "product": {"name": "demo", "title": "Demo"},
        "projects": [
            {"id": "prj.demo.gateway", "name": "gateway", "title": "Gateway"},
            {"id": "prj.demo.hydra", "name": "hydra", "title": "Hydra"},
        ],
        "systems": [
            {
                "id": "sys.demo.gateway.redis",
                "project_id": "prj.demo.gateway",
                "name": "redis",
                "title": "Redis",
            },
            {
                "id": "sys.demo.hydra.redis",
                "project_id": "prj.demo.hydra",
                "name": "redis",
                "title": "Redis",
            },
        ],
        "containers": [
            {
                "id": "ctr.demo.gateway.redis.redis",
                "system_id": "sys.demo.gateway.redis",
                "name": "redis",
                "title": "Redis",
            },
            {
                "id": "ctr.demo.hydra.redis.redis",
                "system_id": "sys.demo.hydra.redis",
                "name": "redis",
                "title": "Redis",
            },
        ],
        "relationships": [],
    }

    files = render_structurizr_model_files(architecture)

    assert 'sys_demo_gateway_redis = softwareSystem "demo / Gateway / Redis"' in files["model/projects/gateway.dsl"]
    assert 'sys_demo_hydra_redis = softwareSystem "demo / Hydra / Redis"' in files["model/projects/hydra.dsl"]
    assert 'softwareSystem "demo / Redis"' not in files["model/projects/gateway.dsl"]
    assert 'softwareSystem "demo / Redis"' not in files["model/projects/hydra.dsl"]
