"""Compatibility facade for Kubernetes client and object helpers."""

from .client import KubectlClient
from .metadata import (
    affinity_summary,
    container_security_inventory,
    probe_summary,
    scheduling_map_summary,
    toleration_summaries,
    topology_spread_summary,
    workload_scheduling_context,
    workload_security_context,
)
from .network import (
    ingress_entrypoints,
    ingress_routes,
    ingress_services,
    service_entrypoints,
    service_matches_workload,
    workload_pods,
)
from .objects import (
    annotations_of,
    configmap_data,
    container_inventory,
    decode_secret_data,
    dict_contains,
    find_related_workloads,
    item_map,
    labels_of,
    obj_name,
    pod_labels_from_template,
    pod_template_annotations_of,
    selector_of_workload,
    service_selector,
    workload_app_service,
    workload_runtime_status,
    workload_service_id,
)

__all__ = [
    "KubectlClient",
    "affinity_summary",
    "annotations_of",
    "configmap_data",
    "container_inventory",
    "container_security_inventory",
    "decode_secret_data",
    "dict_contains",
    "find_related_workloads",
    "ingress_entrypoints",
    "ingress_routes",
    "ingress_services",
    "item_map",
    "labels_of",
    "obj_name",
    "pod_labels_from_template",
    "pod_template_annotations_of",
    "probe_summary",
    "scheduling_map_summary",
    "selector_of_workload",
    "service_entrypoints",
    "service_matches_workload",
    "service_selector",
    "toleration_summaries",
    "topology_spread_summary",
    "workload_app_service",
    "workload_pods",
    "workload_runtime_status",
    "workload_scheduling_context",
    "workload_security_context",
    "workload_service_id",
]
