"""LikeC4 product model renderer."""

from typing import Any, Dict, List

from ...config import LIKEC4_EXTERNAL_ELEMENT_TYPES, clean_metadata_string
from ..generated_paths import unique_generated_path
from .common import likec4_alias, likec4_metadata_lines, likec4_quote
from .model_context import LikeC4ModelContext, container_metadata_items, likec4_model_context
from .model_partitions import (
    external_model_systems,
    orphan_model_systems_by_project,
    project_model_partitions,
    project_model_systems,
)
from .model_partitions import (
    is_external_system as _is_external_system,
)
from .model_resources import (
    diagram_description as _diagram_description,
)
from .model_resources import (
    element_metadata_items as _element_metadata_items,
)
from .model_resources import (
    is_url,
    likec4_container_resource_lines,
    likec4_external_resource_lines,
    likec4_link_label,
    likec4_resource_link_lines,
    likec4_system_description,
    likec4_system_resource_lines,
)


def _is_url(value: str) -> bool:
    return is_url(value)


def likec4_tag_lines(tags: List[str], indent: str = "    ") -> List[str]:
    lines = []
    seen = set()
    for tag in tags:
        raw_tag = clean_metadata_string(tag)
        if not raw_tag:
            continue
        clean_tag = likec4_alias(raw_tag)
        if not clean_tag or clean_tag in seen:
            continue
        seen.add(clean_tag)
        lines.append(f"{indent}#{clean_tag}")
    return lines


def _external_endpoint_element_type(system: Dict[str, Any]) -> str:
    kind = system.get("element_type") or "system"
    if kind in LIKEC4_EXTERNAL_ELEMENT_TYPES and kind not in {"system", "Website"}:
        return kind
    return "External_Endpoint"


def _render_likec4_systems(
    architecture: Dict[str, Any],
    systems: List[Dict[str, Any]],
    *,
    comment: str = "Generated by kmap. Do not edit manually.",
) -> str:
    context = likec4_model_context(architecture)

    lines = [
        "model {",
        f"  // {comment}",
        "",
    ]

    for system in sorted(systems, key=lambda item: item.get("id", "")):
        lines.extend(_render_likec4_system_lines(system, context))

    lines.append("}")
    return "\n".join(lines) + "\n"


def _render_likec4_system_lines(system: Dict[str, Any], context: LikeC4ModelContext) -> List[str]:
    alias = likec4_alias(system.get("id") or system.get("name") or "system")
    title = system.get("title") or system.get("name") or alias
    kind = _likec4_system_kind(system)
    project = context.project_by_id.get(system.get("project_id") or "")
    lines = [likec4_system_header_line(alias, kind, title)]
    lines.extend(_likec4_system_body_lines(system, context, project))
    for container in sorted(
        context.containers_by_system.get(system.get("id") or "", []), key=lambda item: item.get("id", "")
    ):
        lines.extend(_render_likec4_container_lines(container, system, project, context))
    lines.append("  }")
    lines.append("")
    return lines


def _likec4_system_kind(system: Dict[str, Any]) -> str:
    kind = system.get("element_type") or "system"
    return kind if kind in LIKEC4_EXTERNAL_ELEMENT_TYPES else "system"


def _likec4_system_body_lines(
    system: Dict[str, Any],
    context: LikeC4ModelContext,
    project: Dict[str, Any] | None,
) -> List[str]:
    lines = likec4_tag_lines(list((project or {}).get("tags") or []), indent="    ")
    description = likec4_system_description(system, context.project_by_id)
    if description:
        lines.append(f'    description "{likec4_quote(description)}"')
    lines.extend(likec4_metadata_lines(_element_metadata_items(system), indent="    "))
    lines.extend(likec4_system_resource_lines(system, context.project_by_id))
    lines.extend(likec4_external_resource_lines(system))
    return lines


def likec4_system_header_line(alias: str, kind: str, title: str) -> str:
    return f'  {alias} = {kind} "{likec4_quote(title)}" {{'


def _render_likec4_container_lines(
    container: Dict[str, Any],
    system: Dict[str, Any],
    project: Dict[str, Any] | None,
    context: LikeC4ModelContext,
) -> List[str]:
    container_alias = likec4_alias(container.get("id") or container.get("name") or "container")
    container_title = container.get("title") or container.get("name") or container_alias
    container_kind = _likec4_container_kind(container, system)
    lines = [likec4_container_header_line(container_alias, container_kind, container_title)]
    lines.extend(likec4_tag_lines(list((project or {}).get("tags") or []), indent="      "))
    if container.get("technology"):
        lines.append(f'      technology "{likec4_quote(container.get("technology"))}"')
    description = _diagram_description(clean_metadata_string(container.get("description")))
    if description:
        lines.append(f'      description "{likec4_quote(description)}"')
    lines.extend(likec4_metadata_lines(container_metadata_items(container, context), indent="      "))
    lines.extend(likec4_container_resource_lines(container, context.project_by_id, fallback_project=project))
    lines.append("    }")
    return lines


def _likec4_container_kind(container: Dict[str, Any], system: Dict[str, Any]) -> str:
    if container.get("kind") == "external" and _is_external_system(system):
        return _external_endpoint_element_type(system)
    return "container"


def likec4_container_header_line(alias: str, kind: str, title: str) -> str:
    return f'    {alias} = {kind} "{likec4_quote(title)}" {{'


def render_likec4_model(architecture: Dict[str, Any]) -> str:
    return _render_likec4_systems(architecture, architecture.get("systems") or [])


def render_likec4_model_files(architecture: Dict[str, Any]) -> Dict[str, str]:
    systems = architecture.get("systems") or []
    projects = architecture.get("projects") or []
    files: Dict[str, str] = {
        "model/00-external.c4": _render_likec4_systems(
            architecture,
            external_model_systems(systems),
            comment="Generated external dependencies by kmap. Do not edit manually.",
        )
    }

    used_paths: set[str] = set()
    for partition in project_model_partitions(systems, projects):
        path = unique_generated_path(partition.project, used_paths, directory="model/projects", extension="c4")
        files[path] = _render_likec4_systems(
            architecture,
            partition.systems,
            comment=partition.comment,
        )

    return files


__all__ = [
    "external_model_systems",
    "likec4_container_resource_lines",
    "likec4_external_resource_lines",
    "likec4_link_label",
    "likec4_resource_link_lines",
    "likec4_system_description",
    "likec4_system_resource_lines",
    "likec4_tag_lines",
    "orphan_model_systems_by_project",
    "project_model_systems",
    "render_likec4_model",
    "render_likec4_model_files",
]
