"""Static LikeC4 README sections."""

from typing import List


def intro_lines(product_title: str) -> List[str]:
    return [
        f"# {product_title} LikeC4",
        "",
        "Generated by `kmap`. Do not edit generated sections manually; update Kubernetes/config and",
        "regenerate the documentation instead.",
        "",
        "## Summary",
        "",
    ]


def regenerate_lines(config_file: str, product_name: str) -> List[str]:
    return [
        "",
        "## Regenerate",
        "",
        "Run from `tools/kmap`:",
        "",
        "```bash",
        f'python kmap.py run-all --config "{config_file}"',
        "```",
        "",
        "To override the configured renderer explicitly:",
        "",
        "```bash",
        f'python kmap.py run-all --config "{config_file}" --render likec4',
        "```",
        "",
        "## Local Preview",
        "",
        "Preview with the official LikeC4 Docker image:",
        "",
        "```bash",
        f'PRODUCT="{product_name}"',
        'docker run -d --rm --init --name "likec4-${PRODUCT}" \\',
        "  -p 5173:5173 \\",
        '  -v "$(pwd)/../..:/data" \\',
        '  likec4/likec4 start --host 0.0.0.0 "Likec4/${PRODUCT}"',
        "```",
        "",
        "Open:",
        "",
        "```text",
        "http://localhost:5173",
        "```",
        "",
        "Stop preview:",
        "",
        "```bash",
        'docker stop "likec4-${PRODUCT}"',
        "```",
        "",
        "Validate without starting preview:",
        "",
        "```bash",
        f'docker run --rm -v "$(pwd)/../..:/data" likec4/likec4 validate "Likec4/{product_name}"',
        "```",
        "",
        "Build static documentation:",
        "",
        "```bash",
        'docker run --rm -v "$(pwd)/../..:/data" likec4/likec4 build \\',
        f'  --output "/tmp/likec4-{product_name}" \\',
        f'  --base "/{product_name}/" \\',
        f'  "Likec4/{product_name}"',
        "```",
        "",
        "## Projects",
        "",
    ]


def generated_files_lines() -> List[str]:
    return [
        "",
        "## Generated files",
        "",
        "- `likec4.config.json` connects the project to `../common`.",
        "- `model/.kmap-generated.json` tracks generated model fragments for stale-file cleanup.",
        "- `model/00-external.c4` contains generated external systems and endpoint containers.",
        "- `model/projects/<project>.c4` contains generated systems and containers split by project/repository.",
        "- `model/relations/00-external.c4` contains generated external relationships.",
        "- `model/relations/<project>.c4` contains generated internal/cross-project relationships split by source project.",
        "- `views/generated.c4` contains generated views.",
        "- `deployments/<env>.c4` contains generated deployment overlays.",
        "",
    ]


__all__ = ["generated_files_lines", "intro_lines", "regenerate_lines"]
