"""LikeC4 README section builders."""

from typing import Any, Dict, List

from ...model.metadata import KMAP_GENERATOR_NAME, KMAP_GENERATOR_VERSION, KMAP_RULES_FILE
from ..markdown import markdown_table, short_join
from .readme_static_sections import generated_files_lines, intro_lines, regenerate_lines
from .readme_tables import ReadmeTables


def summary_lines(
    context: Dict[str, Any], internal_systems: List[Dict[str, Any]], external_systems: List[Dict[str, Any]]
) -> List[str]:
    product = context["product"]
    generator = context["generator"]
    return markdown_table(
        ["Field", "Value"],
        [
            ["Product", context["product_name"]],
            ["DevOps owner", product.get("owner_team") or "-"],
            ["Domain", product.get("domain") or "-"],
            ["Environment", context["default_env"]],
            ["Generated by", generator.get("tool") or KMAP_GENERATOR_NAME],
            ["Generator version", generator.get("version") or KMAP_GENERATOR_VERSION],
            ["Generated at", context["generated_at"] or "-"],
            ["Config", context["config_file"]],
            ["Rules", generator.get("rules_file") or KMAP_RULES_FILE],
            ["Projects", len(context["projects"])],
            ["Systems", f"{len(internal_systems)} internal / {len(external_systems)} external"],
            ["Containers", len(context["containers"])],
            ["Relationships", len(context["relationships"])],
            ["Traffic flows", len(context["traffic_flows"])],
            ["Inspect reports", context["generation_hints"].get("report_count", "-")],
            ["Workloads", context["generation_hints"].get("workload_count", "-")],
        ],
        max_widths=[24, 86],
    )


def append_table_section(lines: List[str], title: str, table_lines: List[str]) -> None:
    lines.extend(["", f"## {title}", ""])
    lines.extend(table_lines)


def append_project_sections(lines: List[str], tables: ReadmeTables) -> None:
    lines.extend(
        markdown_table(
            ["Project", "DevOps owner", "Systems", "Containers", "Namespaces"],
            tables.project_rows,
            max_widths=[24, 24, 8, 10, 40],
        )
    )
    if tables.project_resource_rows:
        append_table_section(
            lines,
            "Project Resources",
            markdown_table(
                ["Project", "Resource", "URL"],
                tables.project_resource_rows,
                max_widths=[26, 16, 67],
            ),
        )


def append_dependency_sections(lines: List[str], tables: ReadmeTables) -> None:
    lines.extend(
        [
            "",
            "## Dependency Hotspots",
            "",
            "Most referenced nodes by distinct source containers. These are candidates for focused scaling,",
            "monitoring and operational review.",
            "",
        ]
    )
    lines.extend(
        markdown_table(
            ["System", "Kind", "Category", "Distinct source containers", "Incoming relationships"],
            tables.top_incoming_rows,
            max_widths=[34, 16, 18, 26, 22],
        )
    )
    lines.extend(["", "## Top Callers", ""])
    lines.extend(
        markdown_table(
            ["System", "Category", "Outgoing relationships", "Distinct target systems"],
            tables.top_outgoing_rows,
            max_widths=[42, 22, 24, 24],
        )
    )
    lines.extend(["", "## External Dependencies", ""])
    lines.extend(
        markdown_table(
            ["External", "Type", "Relations", "Consumers"],
            tables.external_rows,
            max_widths=[26, 26, 9, 44],
        )
    )
    lines.extend(["", "## External Dependency Evidence", ""])
    lines.extend(
        markdown_table(
            ["External", "Example endpoints/evidence"],
            tables.external_evidence_rows,
            max_widths=[30, 80],
        )
    )


def append_relationship_sections(lines: List[str], tables: ReadmeTables) -> None:
    lines.extend(["", "## Cross-Project Dependencies", ""])
    lines.extend(
        markdown_table(
            ["Source project", "Target project", "Relationships"],
            tables.cross_project_rows,
            max_widths=[44, 44, 13],
        )
    )
    lines.extend(["", "## Relationship Breakdown", ""])
    lines.extend(
        markdown_table(
            ["Type", "Count"], [[key, value] for key, value in sorted(tables.relationship_type_counts.items())]
        )
    )
    lines.extend([""])
    lines.extend(
        markdown_table(["Boundary", "Count"], [[key, value] for key, value in sorted(tables.boundary_counts.items())])
    )


def append_deployment_sections(lines: List[str], tables: ReadmeTables) -> None:
    lines.extend(["", "## Deployment", ""])
    lines.extend(
        markdown_table(
            ["Environment", "Clusters", "Namespaces", "Instances"],
            tables.deployment_rows,
            max_widths=[40, 10, 12, 10],
        )
    )
    if tables.traffic_flow_rows:
        append_table_section(
            lines,
            "Traffic Flows",
            markdown_table(
                ["Direction", "Source", "Namespace", "Route"],
                tables.traffic_flow_rows,
                max_widths=[12, 28, 32, 70],
            ),
        )


def append_followup_section(lines: List[str], tables: ReadmeTables) -> None:
    lines.extend(["", "## Follow-up checklist", ""])
    lines.extend(
        markdown_table(
            ["Check", "Current value"],
            [
                ["Projects without `owner_team`", short_join(tables.missing_owner_projects, limit=8) or "none"],
                [
                    "External systems still using generic `system` type",
                    short_join(tables.generic_external, limit=8) or "none",
                ],
                [
                    "Internal systems still using generic `system` type",
                    short_join(tables.generic_internal, limit=8) or "none",
                ],
            ],
            max_widths=[50, 61],
        )
    )


__all__ = [
    "append_dependency_sections",
    "append_deployment_sections",
    "append_followup_section",
    "append_project_sections",
    "append_relationship_sections",
    "append_table_section",
    "generated_files_lines",
    "intro_lines",
    "regenerate_lines",
    "summary_lines",
]
