"""Structurizr project rendering from the normalized architecture model."""

from pathlib import Path
from typing import Any, Dict, List

from ... import __version__
from ...identifiers import q
from ...io import ensure_dir, load_required_json_file, write_text_atomic
from ...logging import eprint
from ..generated_files import clean_generated_files, write_generated_manifest
from .deployment import render_structurizr_deployment
from .model_files import render_structurizr_model_files
from .views import render_structurizr_views


def render_structurizr_workspace(architecture: Dict[str, Any]) -> str:
    workspace = architecture.get("workspace") or {}
    product = architecture.get("product") or {}
    generator = workspace.get("generator") or {}
    source = workspace.get("source") or {}
    tool = generator.get("tool") or source.get("tool") or "kmap"
    version = generator.get("version") or source.get("version") or __version__
    generated_at = workspace.get("generated_at") or "-"
    config_file = generator.get("config_file") or source.get("config_file") or "-"
    rules_file = generator.get("rules_file") or source.get("rules_file") or "GENERATION_RULES.md"
    product_name = product.get("name") or workspace.get("product") or "product"

    lines: List[str] = [
        f"// Generated by {q(tool)} {q(version)} at {q(generated_at)}",
        f"// Config: {q(config_file)}",
        f"// Rules: {q(rules_file)}",
        "workspace extends ../common/workspace.dsl {",
        f'    name "{q(product_name)}"',
        '    description "Описание архитектуры"',
        "    properties {",
        f'        "kmap.generator" "{q(tool)}"',
        f'        "kmap.generator.version" "{q(version)}"',
        f'        "kmap.generated_at" "{q(generated_at)}"',
        f'        "kmap.config_file" "{q(config_file)}"',
        f'        "kmap.rules_file" "{q(rules_file)}"',
        "    }",
        "    model {",
        "        !include model/projects/",
        "        !include model/external/",
        "        !include model/relations/",
        "        !include deployment/",
        "    }",
        "    views {",
        "        !include view/",
        "    }",
        "}",
    ]
    return "\n".join(lines) + "\n"


def render_structurizr_architecture(args) -> int:
    architecture = load_required_json_file(Path(args.architecture_file))
    output_dir = Path(args.output_dir)
    view_file = output_dir / "view" / "generated.dsl"
    deployment_file = output_dir / "deployment" / "generated.dsl"
    workspace_file = output_dir / "workspace.dsl"

    ensure_dir(output_dir / "model" / "projects")
    ensure_dir(output_dir / "model" / "external")
    ensure_dir(output_dir / "model" / "relations")
    ensure_dir(view_file.parent)
    ensure_dir(deployment_file.parent)
    _clean_generated_model_files(output_dir)
    model_files = render_structurizr_model_files(architecture)
    for relative_path, content in model_files.items():
        target = output_dir / relative_path
        ensure_dir(target.parent)
        write_text_atomic(target, content)
    write_generated_manifest(output_dir, kind="structurizr-model", files=model_files)
    write_text_atomic(view_file, render_structurizr_views(architecture))
    deployment_content = "".join(
        render_structurizr_deployment(architecture, deployment) for deployment in architecture.get("deployments") or []
    )
    write_text_atomic(deployment_file, deployment_content or "# Generated by kmap.py\n")
    write_text_atomic(workspace_file, render_structurizr_workspace(architecture))
    eprint(f"[kmap] wrote Structurizr model fragments from architecture model: {output_dir / 'model'}")
    eprint(f"[kmap] wrote Structurizr view fragment from architecture model: {view_file}")
    eprint(f"[kmap] wrote Structurizr workspace from architecture model: {workspace_file}")
    return 0


def _clean_generated_model_files(output_dir: Path) -> None:
    clean_generated_files(
        output_dir,
        suffix=".dsl",
        force_files=("model/generated.dsl",),
        generated_dirs=("model/projects", "model/external", "model/relations"),
    )


__all__ = ["render_structurizr_architecture", "render_structurizr_workspace"]
